#!/bin/bash

failed=0
for v in WIKI_NAME WIKI_URL DATABASE_URL; do
  if [ -z "${!v}" ]; then
    failed=1
    echo "Missing environment variable $v"
  fi
done
if [ $failed == 1 ]; then
  exit 1
fi

: ${WIKI_META_NAMESPACE:=Meta} ${WIKI_DB_NAME:=mediawiki} ${WIKI_DB_SCHEMA:=mediawiki}

eval "$(python -c "
from pipes import quote
from urlparse import urlparse
import os

url = uriparse(os.getenv('DATABASE_URL'))
user_part, _, host_part = url.netloc.rpartition('@')
host, port = host_part.partition(':')
username, password = user_part.partition(':')
if not port:
  port = '5432'

print 'WIKI_DB_HOST=' + quote(host)
print 'WIKI_DB_PORT=' + quote(port)
print 'WIKI_DB_USER=' + quote(username)
print 'WIKI_DB_PASSWORD=' + quote(password)
")"
